version: 2

build:
  image: latest

formats: all

python:
  version: 3.6
  install:
    - requirements: docs/requirements.txt
    - requirements: requirements.txt
    - requirements: docs/requirements.txt
    - method: pip
      path: .
